name: Publish Documentation
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'mkdocs.yml'
      - 'README.md'
      - 'standard-integration/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
